# Generated by Django 5.2.8 on 2025-11-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(db_index=True, help_text="YouTube video ID (e.g., 'dQw4w9WgXcQ')", max_length=20, unique=True)),
                ('srt_file', models.FileField(blank=True, help_text='SubRip subtitle file (.srt)', upload_to='transcripts/srt/%Y/%m/')),
                ('text_file', models.FileField(blank=True, help_text='Plain text transcript file (.txt)', upload_to='transcripts/text/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transcript',
                'verbose_name_plural': 'Transcripts',
                'ordering': ['-created_at'],
            },
        ),
    ]
