# Generated by Django 5.2.8 on 2025-11-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='srt_file',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='text_file',
        ),
        migrations.AddField(
            model_name='transcript',
            name='srt_content',
            field=models.TextField(blank=True, help_text='SubRip subtitle format content'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='text_content',
            field=models.TextField(blank=True, help_text='Plain text transcript content'),
        ),
    ]
