# Generated by Django 5.2.8 on 2025-11-07 18:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_remove_transcript_srt_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('youtube_id', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('text_content', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('srt_content', config='english', weight='C'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='transcript_search_idx'),
        ),
    ]
