# Generated by Django 5.2.8 on 2025-11-20 22:41

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0003_transcript_search_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_search_type', models.CharField(choices=[('fts', 'Full Text Search'), ('trigram', 'Trigram Search'), ('vector', 'Vector/Semantic Search'), ('hybrid', 'Hybrid Search')], default='hybrid', help_text='Default search type to use', max_length=20)),
                ('fts_weight', models.FloatField(default=0.3, help_text='Weight for Full Text Search results (0-1)')),
                ('trigram_weight', models.FloatField(default=0.3, help_text='Weight for Trigram Search results (0-1)')),
                ('vector_weight', models.FloatField(default=0.4, help_text='Weight for Vector/Semantic Search results (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Configuration',
                'verbose_name_plural': 'Search Configurations',
            },
        ),
        migrations.CreateModel(
            name='SRTSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(db_index=True, help_text='YouTube video ID', max_length=20)),
                ('segment_index', models.IntegerField(help_text='Index of this segment in the transcript')),
                ('start_time', models.CharField(help_text='Start time in HH:MM:SS format', max_length=12)),
                ('end_time', models.CharField(help_text='End time in HH:MM:SS format', max_length=12)),
                ('text', models.TextField(help_text='Segment text content')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for semantic search', null=True)),
                ('embedding_model', models.CharField(default='', help_text='Model used to generate embedding', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transcripts.transcript')),
            ],
            options={
                'verbose_name': 'SRT Segment',
                'verbose_name_plural': 'SRT Segments',
                'ordering': ['transcript', 'segment_index'],
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['text'], name='srtsegment_text_trgm_idx', opclasses=['gist_trgm_ops']), models.Index(fields=['transcript', 'segment_index'], name='transcripts_transcr_2a2581_idx'), models.Index(fields=['youtube_id'], name='transcripts_youtube_0b15d5_idx')],
            },
        ),
    ]
