# Generated by Django 5.2.8 on 2025-11-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0004_searchconfig_srtsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchconfig',
            name='fts_enabled',
            field=models.BooleanField(default=True, help_text='Enable Full Text Search'),
        ),
        migrations.AddField(
            model_name='searchconfig',
            name='trigram_enabled',
            field=models.BooleanField(default=True, help_text='Enable Trigram Search'),
        ),
        migrations.AddField(
            model_name='searchconfig',
            name='vector_enabled',
            field=models.BooleanField(default=False, help_text='Enable Vector/Semantic Search (requires embeddings)'),
        ),
    ]
