# Generated by Django 5.2.8 on 2025-11-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0005_searchconfig_fts_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchconfig',
            name='vector_enabled',
            field=models.BooleanField(default=True, help_text='Enable Vector/Semantic Search (requires embeddings)'),
        ),
    ]
